insert into faa.otp select
Flt_Year::SMALLINT ,
Flt_Quarter::SMALLINT ,
Flt_Month::SMALLINT ,
Flt_DayofMonth::SMALLINT ,
Flt_DayOfWeek::SMALLINT ,
FlightDate::DATE ,
UniqueCarrier,
AirlineID::integer,
Carrier,
FlightNum,
Origin,
OriginCityName,
OriginState,
OriginStateName,
Dest,
DestCityName,
DestState,
DestStateName,
CRSDepTime,
coalesce('0',DepTime )::INTEGER as DepTime,
coalesce('0.00',DepDelay ):: FLOAT  as DepDelay,
coalesce('0.00',DepDelayMinutes ):: FLOAT  as DepDelayMinutes,
coalesce('0',DepartureDelayGroups )::SMALLINT as DepartureDelayGroups,
coalesce('0.00',TaxiOut ):: FLOAT  as TaxiOut,
WheelsOff,
WheelsOn,
coalesce('0.00',TaxiIn ):: FLOAT  as TaxiIn,
CRSArrTime,
coalesce('0',ArrTime )::INTEGER as ArrTime,
coalesce('0.00',ArrDelay ):: FLOAT  as ArrDelay,
coalesce('0.00',ArrDelayMinutes ):: FLOAT  as ArrDelayMinutes,
coalesce('0',ArrivalDelayGroups )::SMALLINT as ArrivalDelayGroups,
coalesce('0.00',Cancelled ):: FLOAT  as Cancelled,
CancellationCode,
coalesce('0.00',Diverted ):: FLOAT  as Diverted,
coalesce('0.00',CRSElapsedTime ):: FLOAT  as CRSElapsedTime,
coalesce('0.00',ActualElapsedTime )::FLOAT as ActualElapsedTime,
coalesce('0.00',AirTime )::FLOAT as AirTime,
coalesce('0.00',Flights )::FLOAT as Flights,
coalesce('0.00',Distance )::FLOAT as Distance,
coalesce('0',DistanceGroup )::SMALLINT as DistanceGroup,
coalesce('0.00',CarrierDelay )::FLOAT as CarrierDelay,
coalesce('0.00',WeatherDelay):: FLOAT as WeatherDelay,
coalesce('0.00',NASDelay):: FLOAT as NASDelay,
coalesce('0.00',SecurityDelay):: FLOAT as SecurityDelay,
coalesce('0.00',LateAircraftDelay):: FLOAT as LateAircraftDelay
from hcatalog.faa.otp;



