insert into faa.otp select
Flt_Year::SMALLINT ,
Flt_Quarter::SMALLINT ,
Flt_Month::SMALLINT ,
Flt_DayofMonth::SMALLINT ,
Flt_DayOfWeek::SMALLINT ,
FlightDate::DATE ,
UniqueCarrier,
AirlineID::integer,
Carrier,
FlightNum,
Origin, -- airport code
OriginCityName,
OriginState,
OriginStateName,
Dest,
DestCityName,
DestState,
DestStateName,
CRSDepTime,
COALESCE(NULLIF(DepTime,'') , '0' ) ::integer,
COALESCE(NULLIF(DepDelay,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(DepDelayMinutes,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(DepartureDelayGroups,'') , '0' ) ::smallint,
COALESCE(NULLIF(TaxiOut,'') , '0' ) :: float :: smallint,
WheelsOff,
WheelsOn,
COALESCE(NULLIF(TaxiIn,'') , '0' ) :: float :: smallint,
CRSArrTime,
ArrTime,
COALESCE(NULLIF(ArrDelay,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(ArrDelayMinutes,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(ArrivalDelayGroups,'') , '0' ) ::smallint,
COALESCE(NULLIF(Cancelled,'') , '0' ) :: float :: smallint,
CancellationCode,
COALESCE(NULLIF(Diverted,'') , '0' ) :: float :: smallint,
COALESCE(NULLIF(CRSElapsedTime,'') , '0' ) :: float :: INTEGER ,
COALESCE(NULLIF(ActualElapsedTime,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(AirTime,'') , '0' ) :: FLOAT8,
COALESCE(NULLIF(Flights,'') , '0' ) :: float :: smallint,
COALESCE(NULLIF(Distance,'') , '0' ) :: FLOAT8,
DistanceGroup::SMALLINT ,
COALESCE(NULLIF(CarrierDelay,'') , '0' ) :: FLOAT,
coalesce(NULLIF(WeatherDelay,''), '0'):: FLOAT,
coalesce(NULLIF(NASDelay,''), '0'):: FLOAT,
coalesce(NULLIF(SecurityDelay,''), '0'):: FLOAT,
coalesce(NULLIF(LateAircraftDelay,''), '0'):: FLOAT
from hcatalog.faa.otp ;

