create external table faa.ext_otp(
Flt_Year smallint,
Flt_Quarter smallint,
Flt_Month smallint,
Flt_DayofMonth smallint,
Flt_DayOfWeek smallint,
FlightDate date,
UniqueCarrier string,
AirlineID int,
Carrier string,
TailNum string,
FlightNum string,
Origin string,
OriginCityName string,
OriginState string,
OriginStateFips string,
OriginStateName string,
OriginWac smallint,
Dest string,
DestCityName string,
DestState string,
DestStateFips string,
DestStateName string,
DestWac smallint,
CRSDepTime string,
DepTime int,
DepDelay float,
DepDelayMinutes float,
DepDel15 float,
DepartureDelayGroups smallint,
DepTimeBlk string,
TaxiOut float,
WheelsOff string,
WheelsOn string,
TaxiIn float,
CRSArrTime string,
ArrTime int,
ArrDelay float,
ArrDelayMinutes float,
ArrDel15 float,
ArrivalDelayGroups smallint,
ArrTimeBlk string,
Cancelled float,
CancellationCode string,
Diverted float,
CRSElapsedTime float,
ActualElapsedTime float,
AirTime float,
Flights float,
Distance float,
DistanceGroup smallint,
CarrierDelay float,
WeatherDelay float,
NASDelay float,
SecurityDelay float,
LateAircraftDelay float,
FirstDepTime string,
TotalAddGTime float,
LongestAddGTime float,
DivAirportLandings float,
DivReachedDest float,
DivActualElapsedTime float,
DivArrDelay float,
DivDistance float,
Div1Airport string,
Div1WheelsOn string,
Div1TotalGTime float,
Div1LongestGTime float,
Div1WheelsOff string,
Div1TailNum string,
Div2Airport string,
Div2WheelsOn string,
Div2TotalGTime float,
Div2LongestGTime float,
Div2WheelsOff string,
Div2TailNum string,
Div3Airport string,
Div3WheelsOn string,
Div3TotalGTime float,
Div3LongestGTime float,
Div3WheelsOff string,
Div3TailNum string,
Div4Airport string,
Div4WheelsOn string,
Div4TotalGTime float,
Div4LongestGTime float,
Div4WheelsOff string,
Div4TailNum string,
Div5Airport string,
Div5WheelsOn string,
Div5TotalGTime float,
Div5LongestGTime float,
Div5WheelsOff string,
Div5TailNum string,
trailer smallint

)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    location '/hdb-tutorials/otp'
tblproperties("skip.header.line.count"="1"); 
;




create table faa.otp as select * from faa.ext_otp;